name: download-data-json
on: [push]
jobs:
  parse-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install the requirements
        run: pip install -r requirements.txt
      - name: Download metadata and filter for NCHS only datasets
        run: |
	 wget https://data.cdc.gov/data.json
         python P0_filter_NCHS_data.py
