# yamllint disable rule:line-length rule:document-start

name: parse-CDC-metadata
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  parse-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install the requirements
        run: pip install -r requirements.txt
      - name: Download metadata and filter for NCHS only datasets
        run: |
         curl --silent https://data.cdc.gov/data.json > data.json
         python P0_filter_NCHS_data.py
         curl --silent "https://dashboard.data.gov/validate?schema=federal-v1.1&output=json&datajson_url=https%3A%2F%2Fdata.cdc.gov%2Fdata.json&qa=true" > federal_validation.json
         python P1_parse_validator.py
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add -f NCHS_raw_datasets.csv
         git add -f NCHS_validiation_errors.csv
         git commit --allow-empty -m "GH Action: Update raw and validation results"
         git push
